language: rust
cache: cargo

git:
  submodules: false

os:
  - osx

rust:
  - stable

sudo: false

before_script:

script:
  - cargo build
  - cargo test
  - cargo doc --no-deps
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo bench ; fi

notifications:
  email:
    on_success: never
