language: rust
rust:
  - stable

git:
  submodules: false
os: osx

cache:
  directories:
    - $TRAVIS_BUILD_DIR/target

before_cache:
  - find $TRAVIS_BUILD_DIR/target/debug -maxdepth 1 -type f -delete


before_script:
  - cargo install rustfmt || true
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then export CC=clang; HOMEBREW_NO_AUTO_UPDATE=1 brew install opencv3; fi

script:
  - cargo fmt -- --write-mode=diff
  - if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then cargo install -f clippy && cargo clippy; fi
  - cargo build
  - cargo test
  - cargo doc --no-deps
  - if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then cargo bench; fi

notifications:
  email:
    on_success: never

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: target/doc/
  on:
    branch: master
