language: rust
cache: cargo

git:
  submodules: false

os:
  - osx

rust:
  - stable

sudo: false

before_script:
  - |
    if [[ $TRAVIS_OS_NAME == "osx" ]]; then
       export CC=clang;
       brew tap homebrew/science
       HOMEBREW_NO_AUTO_UPDATE=1 brew install opencv3
    fi

script:
  - cargo build
  - cargo test
  - cargo doc --no-deps
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo bench ; fi

notifications:
  email:
    on_success: never

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: target/doc/
  on:
    branch: master
