environment:
  RUSTUP_USE_HYPER: 1
  CARGO_HTTP_CHECK_REVOKE: false

  matrix:
  - TARGET: x86_64-pc-windows-msvc

install:
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V
  - cmd: ECHO "INSTALL OPENCV:"
  - cmd: choco install OpenCV

before_build:
  - cmd: IF EXIST C:\OpenCV* CD C:\OpenCV*
  - cmd: SET OPENCV_DIR=%CD%\opencv

build: false

test_script:
  - cargo build
  - cargo test
