[package]
name = "rust_vision"
version = "0.1.0"
authors = ["Ben Zhang <benzh@cs.berkeley.edu>"]
build = "build.rs"

[dependencies]
libc = "0.2.0"
getopts = "0.2"

[build-dependencies]
gcc = "0.3"

[features]
gpu = []

[[bin]]
name = "main"
doc = false
